In [2]:
import pandas as pd 
names = ['sepal-length','sepal-width','petal-length','petal-width','class']
data = pd.read_csv('iris.data',names=names)
data.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
len(data)

150

In [4]:
array = data.values
X = array[:,0:4]
y= array[:,4]

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [6]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [7]:
predictions = neigh.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(confusion_matrix(y_test,predictions))
print(f"\n accuracy score = {accuracy_score(y_test,predictions)*100}")
print(classification_report(y_test,predictions))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]

 accuracy score = 98.0
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       0.94      1.00      0.97        15
 Iris-virginica       1.00      0.94      0.97        16

       accuracy                           0.98        50
      macro avg       0.98      0.98      0.98        50
   weighted avg       0.98      0.98      0.98        50



In [9]:
import numpy as np
x =np.array([5.1,3.5,1.4,0.2]).reshape(1,-1)
print(X_test[1])
print(x)
neigh.predict(x)

[5.7 3.8 1.7 0.3]
[[5.1 3.5 1.4 0.2]]


array(['Iris-setosa'], dtype=object)